version: '3.4'

services:
  makc2020.apps.api.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"


  makc2020.apps.identityserver.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"

