version: '3.4'

services:
  makc2020.apps.api.base:
    image: ${DOCKER_REGISTRY-}makc2020appsapibase
    build:
      context: .
      dockerfile: Makc2020.Apps.Api.Base/Dockerfile

  makc2020.apps.api.web:
    image: ${DOCKER_REGISTRY-}makc2020appsapiweb
    build:
      context: .
      dockerfile: Makc2020.Apps.Api.Web/Dockerfile


  makc2020.apps.identityserver.web:
    image: ${DOCKER_REGISTRY-}makc2020appsidentityserverweb
    build:
      context: .
      dockerfile: Makc2020.Apps.IdentityServer.Web/Dockerfile

